[package]
name = "kix"
version = "0.3.0"
edition = "2021"
description = "A result type for testing that supports to eliminate using of Result::unwrap"
license = "Apache-2.0"
readme = "readme.md"
repository = "https://github.com/kevin-leptons/kix"
